server:
  port: 9000

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
